version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
    ports:
      - "3306:3306"
    restart: always
    